### ISSUE TITLE
cURL issue validating SSL

### ISSUE THREAD

**Issue by Leinad4Mind** [gothick/phpbb-ext-recaptcha2#14]
```
        // prefer curl
        if (function_exists('curl_version'))
        {
            // default cURL options
            // modified from: http://stackoverflow.com/a/6595108
            $opts = array(
                    CURLOPT_HEADER => false,
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_USERAGENT => 'ReCaptcha ' . self::VERSION,
                    CURLOPT_AUTOREFERER => true,
                    CURLOPT_CONNECTTIMEOUT => 60,
                    CURLOPT_TIMEOUT => 60,
                    CURLOPT_MAXREDIRS => 5,
                    CURLOPT_ENCODING => ''
            );
```

I've added this code to work:
`CURLOPT_SSL_VERIFYPEER => false`

Best regards

**Comment by gothick** [comment]
If you need that to make things work, I believe it just means that your PHP server isn't configured properly to validate the Google server's SSL certificate. Certainly it works fine for me without your change, and I'd be wary about turning off SSL certificate validation by default.

It's possible that we should add an option to not validate the Google certificate for those people who don't have enough control over their server environments to fix the real issue...

**Comment by Leinad4Mind** [comment]
Thanks for the information

**Comment by gothick** [comment]
I'm now closing all outstanding issues as phpBB 3.2.x has built-in support for reCAPTCHA 2.
