### ISSUE TITLE
Readme should explain how to install it.

### ISSUE THREAD

**Issue by MrsTonedOne** [gothick/phpbb-ext-recaptcha2#16]

**Comment by gothick** [comment]
If it helps in the meantime, [there are full instructions on extension installation on the phpBB website](https://www.phpbb.com/extensions/installing/). After that you configure it in the same way as the built-in reCAPTCHA module.

**Comment by MrsTonedOne** [comment]
ok, so there's the piece i'm missing. I'm still on 3.0. I didn't know 3.1 included extension support. (it's been over a year since I bothered paying attention to anything in the phpbb community) Might want to instead include a mention that this requires 3.1 and up.

Anywho I just hamfisted 2.0 support into the existing recaptcha plugin.
