### ISSUE TITLE
Imstallation

### ISSUE THREAD

**Issue by dgulliver** [gothick/phpbb-ext-recaptcha2#17]
Hi,

I don't have an issue just some questions.

How do I install? Will this work on phpbb 3.1.9?
I downloaded from phpBB but its been marked as abandoned.

Regards
Darren

**Comment by Galixte** [comment]
Hi @dgulliver,

you can try with a test phpBB board 3.1.9.

With each extension in composer.json file, you can read the correct names for the folders (authorname/extensionname), that you have to create.

This is the line: https://github.com/gothick/phpbb-ext-recaptcha2/blob/master/composer.json#L2.

On your FTP, you have to create two folders, like this: `./ext/gothick/recaptcha2/` inside you have to put all files and folders from the zip downloaded here: https://github.com/gothick/phpbb-ext-recaptcha2/archive/master.zip.

**Comment by gothick** [comment]
Thanks for the help, @Galixte. Incidentally, the pre-made downloadable zip files in [Releases](https://github.com/gothick/phpbb-ext-recaptcha2/releases) already have the correct folders set up inside.

The status of the package as a whole is basically "unofficial". I use this extension regularly on my own board, and it works fine, but it takes a lot of work to get an official package for phpBB even submitted in the first place, let alone to keep it maintained, and at the moment I don't have enough time to devote to that.

**Comment by dgulliver** [comment]
Thanks Guys I installed from URL on s dummy forum and looks great :)

Thanks for pointers and effort you put into this project. 

Darren

**Comment by gothick** [comment]
No problem.
