### ISSUE TITLE
ReCaptcha2 doesn't show for some users

### ISSUE THREAD

**Issue by LanikSJ** [gothick/phpbb-ext-recaptcha2#18]
On my forum if you try to post as guest: https://forums.lanik.us/posting.php?mode=post&f=62 some times a few users see the Captcha and others don't.  Is there a reason for that? How would I go about fixing something like this?

Thanks.

**Comment by gothick** [comment]
I can't think of any reason that would happen. Do you have any way of reliably reproducing the problem? I see the captcha fine there in all my browers...

**Comment by LanikSJ** [comment]
I do not, but some of my users outside of US can.  I don't have access to a proxy or a VPN unfortunately.  I'll see if I can get some of my users to reproduce the problem.

**Comment by gothick** [comment]
Thanks. (I'm outside the US, but no luck for me!)

I notice errors to do with reCAPTCHA in the console on your site that I don't see in my test sites. 
Are there other extensions you have running? It's possible it's got something to do with the in-page login popup you've got? "quick-login-panel"?

Although that popup is hidden, it's there in the page source and has another copy of the reCAPTCHA, which may be confusing things—with "vanilla" phpBB, there would never be more than one reCAPTCHA element on a page, so I've never tested it with more than one. That might be a red herring, though.

**Comment by Galixte** [comment]
Hi,

on your page (in bottom of source) i can see two times this line:

```
<script type="text/rocketscript" data-rocketsrc="https://www.google.com/recaptcha/api.js?hl=en"></script>
```

Why 2 times ?

**Comment by LanikSJ** [comment]
Yes I'm using Quick Login: https://github.com/PayBas/QuickLogin

Here are all of the extensions I have installed: 
![screen shot 2016-11-16 at 3 19 22 pm](https://cloud.githubusercontent.com/assets/12159404/20369829/1eb4a79a-ac10-11e6-953a-e22cd765825c.png)
Quite a few I know. 😞

**Comment by smed79** [comment]
> On my forum if you try to post as guest: 

For me no problem to post a new topic, i get the captcha issue only if i try to rely to 
an existing thread (**Post Reply**) https://vid.me/e/16Xt

**Comment by LanikSJ** [comment]
So the problem is when someone replies to a topic as guest, does that about sum it up?

**Comment by gothick** [comment]
@SMed79 Excellent observation. I can reproduce the problem with a reply to an existing topic, too. Interestingly, I _can't_ reproduce the problem on my test board; the reCAPTCHA 2 shows up fine.

Later today I'll install the Quick Login Panel extension on my test board and see if the multiple copies of the captcha it pulls in are what's causing it. If it is, I'm not sure what the path from there will be, as it'll depend on the exact details of the problem.

**Comment by gothick** [comment]
Okay, I still can't reproduce the issue exactly. However:
- With Quick Login Panel enabled, I get an error in the console when replying to an existing topic: "Error: ReCAPTCHA placeholder element must be empty". I can see a reCAPTCHA on the reply page, but _not_ in the Quick Login Panel. This may indicate that if both reCAPTCHA 2 and Quick Login Panel are enabled, you only get _one_ of the reCAPTCHAs, either the one on the main page _or_ the one in the Quick Login Panel, but not both.
- I can reproduce that problem with phpBB's built-in old-fashioned reCAPTCHA enabled, which _may_ imply that this is a more general problem with JavaScript-based CAPTCHAs and QuickLogin.

<img width="715" alt="yourdomain_com_-_post_a_reply" src="https://cloud.githubusercontent.com/assets/225213/20385303/d76224a4-acae-11e6-971c-0ad00d9865a2.png">

@ierenstein Can you reproduce the original problem yourself with a reply as guest now? If you can, can you try disabling QuickLogin briefly and seeing if the problem goes away? That might be a helpful clue as to what's going on. Thanks!

**Comment by gothick** [comment]
> Hi,
> 
> on your page (in bottom of source) i can see two times this line:
> 
> ```
> <script type="text/rocketscript" data-rocketsrc="https://www.google.com/recaptcha/api.js?hl=en"></script>
> ```
> 
> Why 2 times ?

I can reproduce this by enabling QuickLogin. Which seems a bit odd, really. I'll have to remind myself how the JS inclusion in my extension (and possibly phpBB in general!) works...

**Comment by gothick** [comment]
@ierenstein Can you try the latest release, 1.0.2? I've done a few things that might help compatibility with QuickLogin. Thanks!

**Comment by LanikSJ** [comment]
@gothick I'll try to install a new version and will let you know how it goes.

FWIW I've tried to disable the QuickLogin plugin with and results are the same.

**Comment by smed79** [comment]
Fixed for me 

![lanik.us captcha](http://i.imgur.com/ktriYb9.png)

**Comment by LanikSJ** [comment]
Okay I'm happy to hear that. 👍 

Thanks @gothick @SMed79 😄

**Comment by LanikSJ** [comment]
I just upgraded from 1.0.2 to 1.0.4 and my users are seeing these errors:
http://i.imgur.com/Wv7oCRT.png
http://i.imgur.com/rBMQM8y.png
https://i.gyazo.com/e759601182bbf7157ea3b89e86191b31.png

There are more vids etc starting with this post: https://forums.lanik.us/viewtopic.php?p=110117#p110117

**Comment by gothick** [comment]
That would be a separate problem; I imagine it's because of the move from an older version of Google's reCAPTCHA library to a newer one, which looks like it requires [allow_url_fopen](http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen) to be enabled. I'll raise another issue for this. (But it may not be solved quickly, as I think it probably makes sense to use Google's standard library for reCAPTCHA. You may want to consider enabling allow_url_fopen on your server.)

**Comment by LanikSJ** [comment]
I have very little control over the server since it's on shared hosting.  Take your time I went back to using the earlier version.

**Comment by gothick** [comment]
Okeydokey. I've raised #22 to track this issue.
