### ISSUE TITLE
How do I install the plugin?

### ISSUE THREAD

**Issue by ghost** [gothick/phpbb-ext-recaptcha2#20]
Hey,
I'm sorry for this question, but what parts of the zip file do I need to upload in order to get the captcha working?

Cheers

**Comment by ghost** [comment]
[27-Nov-2016 05:27:21 UTC] PHP Fatal error:  Class 'Symfony\Component\HttpKernel\DependencyInjection\Extension' not found in /home/___/______.com.au/phpbb/di/extension/core.php on line 25

I'm getting this error? any idea on how to fix? My page will not load.

**Comment by ghost** [comment]
https://github.com/gothick/phpbb-ext-recaptcha2/issues/5
I have the same issue as here

**Comment by gothick** [comment]
What version of phpBB are you running, please?

**Comment by ghost** [comment]
Thank you for your prompt reply! I'm running the latest version, 3.1.10

**Comment by gothick** [comment]
I'm now closing all outstanding issues as phpBB 3.2.x has built-in support for reCAPTCHA 2.
