### ISSUE TITLE
PHP Fatal error: Class 'ReCaptcha\\ReCaptcha' not found in /ext/gothick/recaptcha2/captcha/recaptcha2.php on line 260

### ISSUE THREAD

**Issue by Tatiana5** [gothick/phpbb-ext-recaptcha2#21]
See this error when registering, after pressing the "submit" button

Where is class 'ReCaptcha\\ReCaptcha'?
I have not found it in the ext and in the phpBB

**Comment by gothick** [comment]
Sorry; I must have packaged that last release without the correct Composer dependencies. Can you try it again with the latest release, 1.0.4? (ReCaptcha\ReCaptcha is a Google-provided class and *should* be in `vendor`, but wasn't.)

**Comment by Tatiana5** [comment]
It is work. Thanks
