### ISSUE TITLE
newest phpbb version issue

### ISSUE THREAD

**Issue by erfg12** [gothick/phpbb-ext-recaptcha2#5]
Fatal error: Class 'Symfony\Component\HttpKernel\DependencyInjection\Extension' not found in /home/acc/public_html/forum/phpbb/di/extension/core.php on line 25

**Comment by gothick** [comment]
Thanks for the report. I'll try to reproduce this one today, and I'll let you know what I find.

**Comment by erfg12** [comment]
Sorry! I figured it out. If I try to do a MOD install (copy n paste files overwriting old files) it does that. I'm new to this extension installation business.

**Comment by gothick** [comment]
Cool, no problem!
