### ISSUE TITLE
Can't force the language to en

### ISSUE THREAD

**Issue by MAGICCC** [gothick/phpbb-ext-recaptcha2#6]
Hello, 
I am trying to set the language to 'en', so the plugin won't fuck up languages (i.e. german residents get a turkish 'I am not a robot' text)
I changed in captcha/recaptcha2.php following things (line 208)
<code>$recaptcha2_lang = ' ';</code> to <code>$recaptcha2_lang = 'en';</code>

**Comment by vinny** [comment]
You need set the language in https://github.com/gothick/phpbb-ext-recaptcha2/blob/master/language/en/captcha_recaptcha2.php#L25

As per: https://github.com/gothick/phpbb-ext-recaptcha2/blob/master/captcha/recaptcha2.php#L202~L209

``` php
// If we don't have a language code set in our language file, then we don't
// pass anything; reCAPTCHA will attempt to guess the user's language.
```

**Comment by MAGICCC** [comment]
Well 'en' is set as default in that file... So I doubt it's failing somewhere else

**Comment by vinny** [comment]
Try replace theses lines with:

``` php
            // Language code for reCAPTCHA to use
            $recaptcha2_lang = $this->user->lang('GOTHICK_RECAPTCHA2_LANG');
```

**Comment by MAGICCC** [comment]
Looks like it worked. Thanks

**Comment by gothick** [comment]
Incidentally, I've been looking into this this morning, and I can't get the extension to misbehave. With the original code, if I set 'en' in the language file:

```
'GOTHICK_RECAPTCHA2_LANG'                   => 'en', // Use https://developers.google.com/recaptcha/docs/language
```

...then my reCAPTCHA displays in English.

If I turn it back to 'fr' (I'm using the French language file for testing) then my reCAPTCHA displays in French. If I don't have that entry in the language file (for the currently-set board language) at all, then it sends an empty language code string to Google, and that then auto-detects me correctly as English.

I'm therefore not going to make any changes to the code for the plugin--if you're still having problems, please let me know and we can dig a little deeper into it.

(Also, thanks for diving in and helping out!)
